WEBUI/Controllers/ArduinoController.cs
using Arduino;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Controllers;
using WEBUI.Models;
using WEBUI.Providers;

namespace WEBUI.Controllers
{
    public class ArduinoController : Controller
    {


        string Card;

        public ActionResult Index()
        {
           
            ViewBag.Title = "Arduino Get DB 2015";
            return View();
          
        }

        public ActionResult Registrar()
        {

            ViewBag.Title = "Registrar";
            return View();

        }

       
        public JsonResult GetUsers()
        {

            IList<Models.Usuario> list = new UsuariosRepositorio().EncontrarTodos();

            return new JsonResult { Data = list , JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        public JsonResult GetArduino()
        {
            //Nuevo Modelo de Arduino 
            //Esto deberia ser un contexto de acceso a datos
            Card = new ArduinoModel().readData();


            //Aqui voy al repositorio de Usuarios con el # de tarjeta leida arriba 
            //Hay que pasarlo por una interfaz
            Usuario user = new UsuariosRepositorio().EncontrarUsuario(Card);
            string ret = "";
            if (user.Code == null)
            {
                ret = Card;
            }
            else { 
            if ((user.Code == Card) | (user.Code != "") | (user.Code != null))
            {
                ret = "Ya esta registrada";
            }
            else
            {
                ret = Card;
            }
            }

            return new JsonResult { Data = ret, JsonRequestBehavior = JsonRequestBehavior.AllowGet };


        }

        public string Insert(string code, string id, string prop, string aut, string ven)
        {
            String user = new UsuariosRepositorio().InsertarUsuario(code,id,prop,aut,ven);

            if (user == "true")
                return "Inserted";
            else
                return "Not Today Bitch";
        }
      
    }
}

WEBUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html >
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" href="favicon.png" sizes="16x16" type="image/png">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/marchamos")
    <link rel="stylesheet" href="http://css-spinners.com/css/spinner/pulse.css" type="text/css">
    <link type="text/css" rel="stylesheet" href="https://abs.twimg.com/font/gotham-narrow-v3.css" media="all" />
  
</head>
<body onload="//GetArduino();">

    <audio id="xyz"  preload="auto">
        <source src="http://www.freesound.org/data/previews/144/144418_62484-lq.mp3" type="audio/mp3">
    </audio>

  
    <div class="navbar navbar-default navbar-fixed-top ">
        <div class="container ">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Marchamos IMPulse", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, null)
                    </li>
                     <li>@Html.ActionLink("Consultas", "Index", "Arduino", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Registro", "Registrar", "Arduino", new { area = "" }, null)</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" >
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - IMPulse</p>
        </footer>
    </div>
   
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>!function (d, s, id) { var js, fjs = d.getElementsByTagName(s)[0], p = /^http:/.test(d.location) ? 'http' : 'https'; if (!d.getElementById(id)) { js = d.createElement(s); js.id = id; js.src = p + "://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs); } }(document, "script", "twitter-wjs");</script>

</body>
</html>